export enum GetAllBrokersActionTypes {
    API_RESPONSE_SUCCESS = '@@GET_ALL_BROKERS/API_RESPONSE_SUCCESS',
    API_RESPONSE_ERROR = '@@GET_ALL_BROKERS/API_RESPONSE_ERROR',

    GET_ALL_BROKERS = "GET_ALL_BROKERS",
    GET_ALL_BROKERS_LOADING = "GET_ALL_BROKERS_LOADING",
    GET_ALL_BROKERS_ERROR = "GET_ALL_BROKERS_ERROR",
}